import esbuild from "esbuild";
import process from "node:process";
import builtins from "builtin-modules";

const banner =
  "/* eslint-disable */\n" +
  "// This file is generated by esbuild and bundled for Obsidian.\n";

const prod = process.argv.includes("production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: ["obsidian", "electron", "@codemirror/*", ...builtins],
  format: "cjs",
  logLevel: "info",
  minify: prod,
  outfile: "main.js",
  platform: "browser",
  sourcemap: prod ? false : "inline",
  target: "es2018",
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
